### ISSUE TITLE
Package is discontinued until Mastodon provides an OpenAPI spec

### ISSUE THREAD

**Issue by lukepighetti** [lukepighetti/mastodon_dart#39]
After some internal discussions we decided that we are no longer willing to support `mastodon_dart`. The reason is because keeping up with the Mastodon API is too much work without them having an official OpenAPI spec. If the Mastodon team decides to make an OpenAPI spec available we will reconsider supporting `mastodon_dart`.

Related: https://github.com/tootsuite/mastodon/issues/1404

**Comment by maks** [comment]
I'm planning on using this for some Mastodon projects in Dart/Flutter.

@lukepighetti given this issue and Mastodon devs show no signs of wanting to use OPenAPI, would you like to hand over maintainership of this repo/pkg or should I just kick off my own fork?

**Comment by maks** [comment]
@lukepighetti  reply (for some reason he couldnt comment here):
![image](https://user-images.githubusercontent.com/71999/200716477-e880463b-f0cc-4979-9c44-e74b5b4c2126.png)

Thats fair enough. My notoriously short attention span may mean I don't get far with it either. but my personal view is that Twitter is now in a terminal decline and I intend to move over to Mastodon as much as possible, so I want to make a few "comfort features" for myself there and of course do it using Dart. \

From what I can tell, Mastodons dev pace of its API doesn't seem very fast and with the recent huge influx of new users I suspect it will get even slower so I'm happy to have a go. 

It would be preferable if you would be willing to unarchive the pkg but otherwise I'm happy to fork it, I just find that having a long established pub pkg is less confusing for people. Hopefully you can comment again here but if not I'm @mklin@mastodon.social

**Comment by GroovinChip** [comment]
> @lukepighetti  reply (for some reason he couldnt comment here):
> 
> ![image](https://user-images.githubusercontent.com/71999/200716477-e880463b-f0cc-4979-9c44-e74b5b4c2126.png)
> 
> 
> 
> Thats fair enough. My notoriously short attention span may mean I don't get far with it either. but my personal view is that Twitter is now in a terminal decline and I intend to move over to Mastodon as much as possible, so I want to make a few "comfort features" for myself there and of course do it using Dart. \
> 
> 
> 
> From what I can tell, Mastodons dev pace of its API doesn't seem very fast and with the recent huge influx of new users I suspect it will get even slower so I'm happy to have a go. 
> 
> 
> 
> It would be preferable if you would be willing to unarchive the pkg but otherwise I'm happy to fork it, I just find that having a long established pub pkg is less confusing for people. Hopefully you can comment again here but if not I'm @mklin@mastodon.social
> 
> 

My take is that you should fork, and if you find that you are regularly working on it for about 3 months, open a PR back to us and we'll consider unarchiving so you can regularly contribute. @lukepighetti thoughts?

**Comment by lukepighetti** [comment]
That works for me

**Comment by maks** [comment]
It seems that @jtmuller5 is already off and running with the ball in his fork:  https://github.com/jtmuller5/mastodon_dart

@jtmuller5 will you be submitting a PR to this repo with your updates?

**Comment by jtmuller5** [comment]
Hi @maks! I'm definitely open to submitting a PR. I can probably get it in tomorrow afternoon

**Comment by lukepighetti** [comment]
@jtmuller5 we have a null safety branch here: https://github.com/lukepighetti/mastodon_dart/pull/40

**Comment by lukepighetti** [comment]
[mastodon_dart](https://pub.dev/packages/mastodon_dart) is no longer discontinued on pub.dev
